name: Build and test

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        
        - name: making build directory
        shell: bash
        run: mkdir build
            
        - name: cmake configure
        run: -DCMAKE_BUILD_TYPE=Release ..
        working-directory: build
        
        - name: cmake build
        shell: bash
        run: cmake --build .
        working-directory: build

        - name: cmake test
        run: ctest --output-on-failure
        working-directory: build_dir
