name: Build and test

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        
        - name: making build directory
          run: mkdir build
            
        - name: cmake configure
          run: cmake -DCMAKE_BUILD_TYPE=Release ..
          working-directory: build
        
        - name: cmake build
          run: cmake --build .
          working-directory: build

        - name: cmake test
          run: ctest --output-on-failure
          working-directory: build
